In [1]:
# Imports

import numpy as np
from PIL import Image

In [53]:
# Convert pixel array to pixel arrays of edges

#return (top, left, bottom, right) 
def pixel_array_to_edges(pixel_val_array, edge_depth):
    left_edge = pixel_val_array[:, :edge_depth]     # left edge
    print(left_edge)
    right_edge = pixel_val_array[:, -edge_depth:]   # right edge
    right_edge = right_edge[:, ::-1]            # Invert
    print(right_edge)
    top_edge = pixel_val_array[:edge_depth, :].T      # top edge and transpose
    print(top_edge)
    bottom_edge = pixel_val_array[-edge_depth:, :].T # bottom edge and transpose
    bottom_edge = bottom_edge[:, ::-1]
    print(bottom_edge)
    return (left_edge, right_edge, top_edge, bottom_edge)



In [91]:
# Convert single pixel array to pixel value
def convolve_arrays(pixel_val_array, conv_matrix, matrix_sum):
    if pixel_val_array.shape != conv_matrix.shape:
        raise Exception(
            F"pixel array and conv shape do not match{pixel_val_array.shape} != {conv_matrix.shape}")

    return np.sum(np.multiply(pixel_val_array, conv_matrix))/(matrix_sum)


test_image = np.array([[1, 2, 7],
                       [3, 4, 8],
                       [5, 6, 9]])
conv_matrix = np.array([[0, 1, 0],
                        [1, 0, 1],
                        [0, 1, 0]])
print(convolve_arrays(test_image, conv_matrix, 4))


4.75


In [99]:
# Convert a single edge to pixel values

def apply_conv_to_edge(edge, conv_matrix, conv_matrix_sum, pixels_per_edge):
    step_size = int(len(edge)/pixels_per_edge)
    # print(edge[0])

    led_vals = []
    for i in range(0, pixels_per_edge):
        # print(i*step_size)
        led_vals.append(round(convolve_arrays(edge[i*step_size:(i*step_size+len(conv_matrix)), :], conv_matrix, conv_matrix_sum)))
        
    return led_vals

test_array = np.array([
    [1, 2],
    [4, 5],
    [7, 8],
    [5, 6],
    [5, 4],
    [1, 2],
    [4, 5],
    [7, 8],
    [7, 8]])
conv = np.array([[0, 1],
                [1, 0],
                [0, 1]])
print(apply_conv_to_edge(test_array, conv,3, 3))


[5, 4, 7]


In [54]:
test_array = np.array([
    [1, 2, 3, 9, 8],
    [4, 5, 6, 7, 2],
    [7, 8, 9, 9, 1],
    [5, 6, 7, 8, 9],
    [5, 4, 3, 2, 1]])

pixel_array_to_edges(test_array, 2)


[[1 2]
 [4 5]
 [7 8]
 [5 6]
 [5 4]]
[[8 9]
 [2 7]
 [1 9]
 [9 8]
 [1 2]]
[[1 4]
 [2 5]
 [3 6]
 [9 7]
 [8 2]]
[[5 5]
 [4 6]
 [3 7]
 [2 8]
 [1 9]]


In [ ]:
# Run it

# load the image and convert into
# numpy array
img = Image.open('Sample.png')
numpydata = np.asarray(img)
 
# data
print(numpydata)